language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  except:
    - gh-pages

install:
  - composer install

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml